/** data-testid values shared by the UI and the e2e/QA drivers; each value is the kebab-case of its key. */
export const TESTID = {
  appFrame: "app-frame",
  sidebar: "sidebar",
  newSession: "new-session",
  workspaceGroup: "workspace-group",
  threadRow: "thread-row",
  threadMenu: "thread-menu",
  openSettings: "open-settings",
  connectionDot: "connection-dot",
  conversation: "conversation",
  conversationHeader: "conversation-header",
  emptyHero: "empty-hero",
  turn: "turn",
  turnError: "turn-error",
  userMessage: "user-message",
  assistantMessage: "assistant-message",
  reasoning: "reasoning",
  toolCard: "tool-card",
  approvalCard: "approval-card",
  approvalAccept: "approval-accept",
  approvalAcceptSession: "approval-accept-session",
  approvalDecline: "approval-decline",
  questionCard: "question-card",
  questionOption: "question-option",
  questionOtherInput: "question-other-input",
  questionSubmit: "question-submit",
  workingIndicator: "working-indicator",
  historyError: "history-error",
  composer: "composer",
  composerInput: "composer-input",
  composerSend: "composer-send",
  composerStop: "composer-stop",
  modelPicker: "model-picker",
  modelOption: "model-option",
  workspaceChip: "workspace-chip",
  settingsDialog: "settings-dialog",
  settingsThemeSystem: "settings-theme-system",
  settingsThemeLight: "settings-theme-light",
  settingsThemeDark: "settings-theme-dark",
  settingsLanguage: "settings-language",
  diagnostics: "diagnostics",
  restartOmo: "restart-omo",
  reinstallOmo: "reinstall-omo",
  onboarding: "onboarding",
  onboardingCopy: "onboarding-copy",
  onboardingInstall: "onboarding-install",
  onboardingRetry: "onboarding-retry",
  installLog: "install-log",
  connectionBanner: "connection-banner",
  noticeToast: "notice-toast",
} as const;

export type TestId = (typeof TESTID)[keyof typeof TESTID];
