import { expect, test } from "@playwright/test";
import { byTestId, launchApp, shot, tempDir } from "./helpers.ts";
import { TESTID } from "../src/ui/testids.ts";

test("child agents have independent tabs and native task messages without switching the main session", async () => {
  const launched = await launchApp({ omo: "fake", pickDir: tempDir("agent-workspace-project"), size: { width: 1440, height: 900 } });
  const { page } = launched;
  try {
    await byTestId(page, TESTID.newSession).click();
    const projectNew = page.getByTestId("project-new");
    if (await projectNew.count() > 0) await projectNew.click();
    await expect(page.locator('[data-testid="thread-row"][aria-current="page"]')).toBeVisible();
    const mainInput = byTestId(page, TESTID.composerInput);
    await mainInput.fill("SCENARIO:workflow-background");
    await byTestId(page, TESTID.composerSend).click();
    const workspace = page.getByTestId("agent-workspace");
    await expect(workspace).toHaveAttribute("data-placement", "docked");
    await expect(page.getByTestId("agent-panel-toggle")).toBeHidden();
    const parentId = await workspace.getAttribute("data-parent-id");
    const first = workspace.getByTestId("agent-chat-tab").first();
    await expect(first).toBeVisible();
    await expect(workspace.getByTestId("agent-chat-history")).toContainText("Read protocol");
    const taskId = await first.getAttribute("data-task-id");
    const input = workspace.locator("textarea");
    await input.fill("Only this child receives this instruction");
    await workspace.locator('button[type="submit"]').click();
    await expect(input).toHaveValue("");
    const deliveries = launched.readFakeLog().filter(entry => entry.method === "extension_request" && (entry.params as { name?: string })?.name === "omo-ui.task.send");
    expect(deliveries).toHaveLength(1);
    expect(deliveries[0]?.params).toEqual({ threadId: parentId, name: "omo-ui.task.send", data: { taskId, message: "Only this child receives this instruction" } });
    await expect(mainInput).toBeVisible();
    await input.fill("draft stays with this agent");
    await page.getByTestId("right-tab-workflow").click();
    await page.getByTestId("right-tab-agents").click();
    await expect(input).toHaveValue("draft stays with this agent");
    const second = workspace.getByTestId("agent-chat-tab").nth(1);
    await second.click();
    await expect(input).toHaveValue("");
    await input.fill("a separate draft for agent two");
    await first.click();
    await expect(input).toHaveValue("draft stays with this agent");
    const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("omo-ui.agent-workspace.v1") ?? "{}"));
    expect(Object.keys(stored[String(parentId)].drafts)).toHaveLength(2);
    await page.evaluate(() => document.body.setAttribute("data-ds-dark-theme", ""));
    await expect(page.locator("body")).toHaveAttribute("data-ds-dark-theme", "");
    await shot(page, "agent-workspace-dark-desktop");
    await page.evaluate(() => document.body.removeAttribute("data-ds-dark-theme"));
    await expect(page.locator("body")).not.toHaveAttribute("data-ds-dark-theme", "");
    await shot(page, "agent-workspace-light-desktop");
    await launched.app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]?.setSize(1000, 900); });
    await expect.poll(() => page.evaluate(() => window.innerWidth)).toBeLessThan(1100);
    await expect(workspace).toHaveAttribute("data-placement", "docked");
    await expect(mainInput).toBeVisible();
    await shot(page, "agent-workspace-medium");
    await launched.app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]?.setSize(700, 900); });
    await expect(workspace).toHaveAttribute("data-placement", "overlay");
    await expect(input).toHaveValue("draft stays with this agent");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await shot(page, "agent-workspace-narrow");
    await page.getByTestId("right-dock-close").click();
    await expect(workspace).toBeHidden();
    await expect(mainInput).toBeVisible();
    await shot(page, "agent-workspace-narrow-closed");
    await launched.app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]?.setSize(1440, 900); });
    await page.getByTestId("agent-panel-toggle").click();
    await expect(workspace).toHaveAttribute("data-placement", "docked");
  } finally { await launched.close(); }
});
