import { test, expect } from "@playwright/test";
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { launchApp, newSession, send, tempDir, threadRow, shot, setTheme } from "./helpers.ts";

test("agent-created sessions stay separate, searchable and reopen their original session", async () => {
  const home = tempDir("agent-origin-home"), workspace = tempDir("agent-origin-workspace"), userData = tempDir("agent-origin-user");
  const { app, page } = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
  try {
    const user = await newSession(page);
    await send(page, "question-contract ordinary user conversation");
    await expect(page.getByTestId("assistant-message").last()).toContainText("question-contract ordinary user conversation");
    const agent = await page.evaluate(async cwd => {
      const result = await window.omo.request("thread/start", { cwd });
      await window.omo.request("thread/name/set", { threadId: result.thread.id, name: "자동 생성 검증 세션" });
      return result.thread;
    }, workspace);
    appendFileSync(agent.path!, JSON.stringify({ type: "custom", customType: "rpc_client_message_admission", data: { clientMessageId: `probe-owner:${agent.id}`, clientTurnId: `probe-owner:${agent.id}`, durableSessionId: agent.id } }) + "\n");
    await page.reload();
    await page.getByTestId("native-sessions-open").click();
    const native = page.locator(`[data-testid="native-session-row"][data-thread-id="${agent.id}"]`);
    await expect(native).toContainText("Created by an agent");
    await page.getByTestId("native-sessions-close").click();
    await expect(threadRow(page, agent.id)).toHaveCount(0);
    await expect(threadRow(page, user)).toBeVisible();
    await expect(page.getByTestId("workspace-group").getByTestId("thread-row")).toHaveCount(1);
    await page.getByTestId("native-sessions-open").click();
    await native.getByTestId("native-session-manage").click();
    await page.getByTestId("native-sessions-close").click();
    await expect(threadRow(page, agent.id)).toHaveAttribute("data-creator", "agent");
    for (const theme of ["light", "dark"] as const) {
      await setTheme(page, theme);
      await shot(page, `agent-sessions-${theme}-desktop`);
    }
    await page.getByTestId("sidebar-search").fill("自動-not-a-match");
    await expect(page.getByTestId("sidebar-no-match")).toBeVisible();
    await page.getByTestId("sidebar-search").fill("자동 생성");
    await expect(threadRow(page, agent.id)).toHaveCount(1);
    await expect(threadRow(page, user)).toHaveCount(0);
    await threadRow(page, agent.id).getByRole("button").first().click();
    await expect(threadRow(page, agent.id)).toHaveAttribute("aria-current", "page");
    await page.getByTestId("sidebar-search").fill("");
    await page.reload();
    await threadRow(page, agent.id).getByRole("button").first().click();
    await expect(threadRow(page, agent.id)).toHaveAttribute("aria-current", "page");
    await threadRow(page, agent.id).getByTestId("thread-menu").click();
    await page.getByRole("menuitem", { name: "Creator: I created this session" }).click();
    await expect(page.getByTestId("workspace-group").getByTestId("thread-row")).toHaveCount(2);
    await threadRow(page, agent.id).getByTestId("thread-menu").click();
    await page.getByRole("menuitem", { name: "Creator: An agent created this session" }).click();
    await expect(threadRow(page, agent.id)).toHaveAttribute("data-creator", "agent");
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(640, 850));
    await expect(page.getByTestId("header-sidebar-toggle")).toBeVisible();
    await page.getByTestId("header-sidebar-toggle").click();
    await shot(page, "agent-sessions-dark-narrow");
    await page.getByTestId("open-settings").click();
    await page.getByTestId("settings-nav-toggle").click();
    await page.locator('[data-section="appearance"]').click();
    await page.getByTestId("settings-theme-light").click();
    await expect(page.locator("body")).not.toHaveAttribute("data-ds-dark-theme");
    await page.keyboard.press("Escape");
    await page.getByTestId("header-sidebar-toggle").click();
    await expect(threadRow(page, agent.id)).toBeVisible();
    await shot(page, "agent-sessions-light-narrow");
    const listed = await page.evaluate(async () => (await window.omo.request("thread/list", { limit: 100 })).data.map(t => t.id).sort());
    expect(listed).toEqual([user, agent.id].sort());
  } finally { await app.close(); }
});

test("creator evidence records UI creation, keeps old sessions unknown and persists explicit classification", async () => {
  const home = tempDir("creator-home"), workspace = tempDir("creator-workspace"), userData = tempDir("creator-user");
  const { app, page } = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
  try {
    const main = await newSession(page);
    await expect(threadRow(page, main)).toHaveAttribute("data-creator", "user");
    const initial = await page.evaluate(() => window.omo.getPreferences());
    expect(initial.threadCreators?.[main]).toEqual({ origin: "user", source: "ui-new-session" });
    expect(initial.managedThreadIds).toEqual([main]);
    const old = await page.evaluate(async cwd => (await window.omo.request("thread/start", { cwd })).thread, workspace);
    await page.evaluate(async id => window.omo.request("thread/name/set", { threadId: id, name: "Historical session without creator evidence" }), old.id);
    const original = readFileSync(old.path!, "utf8");
    const dori = await page.evaluate(async cwd => (await window.omo.request("thread/start", { cwd })).thread, workspace);
    await page.evaluate(async id => window.omo.request("thread/name/set", { threadId: id, name: "Owner request relayed by Dori" }), dori.id);
    appendFileSync(dori.path!, JSON.stringify({ type: "custom", customType: "rpc_client_message_admission", data: { clientMessageId: "discord:1557620286520696913", durableSessionId: dori.id } }) + "\n");
    await page.reload();
    await expect(threadRow(page, old.id)).toHaveCount(0);
    await page.getByTestId("native-sessions-open").click();
    for (const id of [old.id, dori.id]) await page.locator(`[data-testid="native-session-row"][data-thread-id="${id}"]`).getByTestId("native-session-manage").click();
    await page.getByTestId("native-sessions-close").click();
    await expect(threadRow(page, old.id)).toHaveAttribute("data-creator", "unknown");
    await expect(threadRow(page, dori.id)).toHaveAttribute("data-creator", "dori");
    for (const theme of ["light", "dark"] as const) {
      await setTheme(page, theme);
      await shot(page, `session-creator-${theme}-desktop`);
    }
    await threadRow(page, old.id).getByTestId("thread-menu").click();
    await page.getByRole("menuitem", { name: "Creator: I created this session" }).click();
    await expect(threadRow(page, old.id)).toHaveAttribute("data-creator", "user");
    await page.reload();
    await expect(threadRow(page, old.id)).toHaveAttribute("data-creator", "user");
    const saved = await page.evaluate(() => window.omo.getPreferences());
    expect(saved.threadOrigins?.[old.id]).toBe("user");
    expect(saved.threadCreators?.[old.id]).toBeUndefined();
    await threadRow(page, old.id).getByTestId("thread-menu").click();
    await page.getByRole("menuitem", { name: "Creator: Unknown" }).click();
    await expect(threadRow(page, old.id)).toHaveAttribute("data-creator", "unknown");
    expect(readFileSync(old.path!, "utf8")).toBe(original);
    await threadRow(page, old.id).getByTestId("thread-menu").click();
    await page.getByRole("menuitem", { name: "Remove from managed list", exact: true }).click();
    await expect(threadRow(page, old.id)).toHaveCount(0);
    await page.reload();
    await expect(threadRow(page, old.id)).toHaveCount(0);
    await page.getByTestId("native-sessions-open").click();
    await page.getByTestId("native-sessions-search").fill(old.id);
    const oldNative = page.locator(`[data-testid="native-session-row"][data-thread-id="${old.id}"]`);
    await expect(oldNative).toContainText("Creator unknown");
    await expect(oldNative.getByTestId("native-session-manage")).toHaveAttribute("aria-pressed", "false");
    await oldNative.getByTestId("native-session-manage").click();
    await oldNative.getByRole("button", { name: "Open conversation" }).click();
    await expect(threadRow(page, old.id)).toHaveAttribute("aria-current", "page");
    expect(readFileSync(old.path!, "utf8")).toBe(original);
    const nativeIds = await page.evaluate(async () => (await window.omo.request("thread/list", { limit: 100 })).data.map(t => t.id).sort());
    expect(nativeIds).toEqual([main, old.id, dori.id].sort());
    await page.getByTestId("native-sessions-open").click();
    await page.getByTestId("native-sessions-search").fill("Historical");
    await shot(page, "managed-native-dark-dialog-desktop");
    await page.getByTestId("native-sessions-close").click();
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(640, 850));
    await page.getByTestId("header-sidebar-toggle").click();
    await shot(page, "session-creator-dark-narrow");
    await page.keyboard.press("Escape");
    await setTheme(page, "light");
    await page.getByTestId("header-sidebar-toggle").click();
    await shot(page, "session-creator-light-narrow");
    await page.getByTestId("native-sessions-open").click();
    await shot(page, "managed-native-light-dialog-narrow");
    await page.getByTestId("native-sessions-close").click();
  } finally { await app.close(); }
});

test("native work and related sessions stay under their parent and persist without rewriting sessions", async () => {
  const home = tempDir("related-home"), workspace = tempDir("related-workspace"), userData = tempDir("related-user");
  let launched = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
  try {
    const page = launched.page;
    const parent = await newSession(page);
    await send(page, "main related work");
    const store = path.join(workspace, ".omo", "senpi-task", "tasks");
    mkdirSync(store, { recursive: true });
    writeFileSync(path.join(store, "task.json"), JSON.stringify({ task_id: "task-child", parent_session_id: parent, status: "completed", description: "work", task_summary: "native child work", execution_mode: "in-process", model: "provider/model", residency_state: "persisted_only", depth: 1, created_at: "2026-10-07T00:00:00Z", updated_at: "2026-10-07T00:00:01Z" }));
    await page.reload();
    await threadRow(page, parent).getByRole("button").first().click();
    await expect(page.getByTestId("agent-workspace")).toContainText("native child work");
    await expect(page.getByTestId("agent-chat-tab")).toHaveAttribute("data-task-id", "task-child");
    await expect(page.getByTestId("agent-chat-history")).toBeVisible();
    await page.getByTestId("right-dock-close").click();
    await expect(page.getByTestId("agent-workspace")).toHaveCount(0);
    await page.getByTestId("sidebar-search").fill("native child work");
    await expect(threadRow(page, parent)).toBeVisible();
    await expect(page.getByTestId("thread-child-task")).toHaveCount(0);
    await expect(threadRow(page, parent).locator("..").getByTestId("thread-children-toggle")).toHaveCount(0);
    await expect(threadRow(page, parent).locator("..").getByTestId("thread-children")).toHaveCount(0);
    await page.getByTestId("sidebar-search").fill("");
    await threadRow(page, parent).locator('[data-testid="thread-menu"]').click();
    await page.getByRole("menuitem", { name: "New related session", exact: true }).click();
    await send(page, "child related work");
    const preferences = await page.evaluate(() => window.omo.getPreferences());
    const child = Object.keys(preferences.threadParents)[0]!;
    await expect(threadRow(page, child)).toBeVisible();
    await expect(threadRow(page, child)).toHaveAttribute("aria-current", "page");
    const toggle = threadRow(page, parent).locator("..").getByTestId("thread-children-toggle");
    await expect(toggle).toHaveAttribute("aria-expanded", "true");
    await threadRow(page, parent).getByRole("button").first().click();
    await toggle.click();
    await expect(threadRow(page, child)).toHaveCount(0);
    await page.getByTestId("sidebar-search").fill("child related work");
    await expect(threadRow(page, child)).toBeVisible();
    await expect(toggle).toHaveAttribute("aria-expanded", "true");
    await page.getByTestId("sidebar-search").fill("native child work");
    await expect(threadRow(page, parent)).toBeVisible();
    await expect(threadRow(page, child)).toBeVisible();
    await expect(page.getByTestId("thread-child-task")).toHaveCount(0);
    await expect(threadRow(page, parent)).toHaveAttribute("aria-current", "page");
    await page.getByTestId("sidebar-search").fill("");
    await page.reload();
    await expect(threadRow(page, parent)).toBeVisible();
    if (await toggle.getAttribute("aria-expanded") !== "true") await toggle.click();
    await expect(threadRow(page, child)).toBeVisible();
    await expect(toggle).toHaveAttribute("aria-expanded", "true");
    await expect(threadRow(page, child)).toBeVisible();
    await expect(page.getByTestId("thread-child-task")).toHaveCount(0);
    await threadRow(page, child).getByRole("button").first().click();
    await expect(threadRow(page, child)).toHaveAttribute("aria-current", "page");
    await expect(page.getByTestId("assistant-message").last()).toContainText("child related work");
    await shot(page, "related-sessions-light");
    await setTheme(page, "dark");
    await shot(page, "related-sessions-dark");
    await launched.app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(640, 760));
    await shot(page, "related-sessions-narrow-dark");
    await page.getByTestId("header-sidebar-toggle").click();
    await page.getByTestId("open-settings").click();
    await page.getByTestId("settings-nav-toggle").click();
    await page.locator('[data-section="appearance"]').click();
    await page.getByTestId("settings-theme-light").click();
    await expect(page.locator("body")).not.toHaveAttribute("data-ds-dark-theme");
    await page.keyboard.press("Escape");
    await shot(page, "related-sessions-narrow-light");
    await launched.app.close();
    launched = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
    await expect(threadRow(launched.page, parent)).toBeVisible();
    const restoredToggle = threadRow(launched.page, parent).locator("..").getByTestId("thread-children-toggle");
    if (await restoredToggle.getAttribute("aria-expanded") !== "true") await restoredToggle.click();
    await expect(threadRow(launched.page, child)).toBeVisible();
    const threads = await launched.page.evaluate(async () => (await window.omo.request("thread/list", { limit: 100 })).data);
    expect(threads.map(t => t.id).sort()).toEqual([parent, child].sort());
    expect(threads.every(t => t.cwd === workspace)).toBe(true);
  } finally { await launched.app.close(); }
});

test("native inventory pages reveal older sessions and managed IDs survive app relaunch", async () => {
  const home = tempDir("managed-pages-home"), workspace = tempDir("managed-pages-workspace"), userData = tempDir("managed-pages-user");
  let launched = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
  try {
    const page = launched.page;
    const ids = await page.evaluate(async cwd => {
      const ids: string[] = [];
      for (let i = 0; i < 52; i++) ids.push((await window.omo.request("thread/start", { cwd })).thread.id);
      return ids;
    }, workspace);
    const older = await page.evaluate(async ids => {
      const firstPage = await window.omo.request("thread/list", { limit: 50 });
      return ids.find(id => !firstPage.data.some(thread => thread.id === id));
    }, ids);
    expect(older).toBeTruthy();
    if (older === undefined) throw new Error("Expected a native session outside the first inventory page");
    await page.evaluate(async id => window.omo.request("thread/name/set", { threadId: id, name: "Older inventory search target" }), older);
    await page.reload();
    await expect(page.getByTestId("thread-row")).toHaveCount(0);
    await page.getByTestId("native-sessions-open").click();
    await expect(page.getByTestId("native-session-row")).toHaveCount(50);
    const row = page.locator(`[data-testid="native-session-row"][data-thread-id="${older}"]`);
    await expect(row).toHaveCount(0);
    await page.getByTestId("native-sessions-search").fill(older);
    await expect(row).toBeVisible();
    await expect(page.getByTestId("native-sessions-more")).toHaveCount(0);
    await expect(page.getByTestId("native-sessions-search")).toBeFocused();
    await page.getByTestId("native-sessions-search").fill("Older inventory search target");
    await expect(row).toBeVisible();
    await expect(page.getByTestId("native-session-row")).toHaveCount(1);
    await page.getByTestId("native-sessions-search").fill(workspace);
    await expect(page.getByTestId("native-session-row")).toHaveCount(52);
    await page.getByTestId("native-sessions-search").fill("no-native-result-for-this-query");
    await expect(page.getByTestId("native-session-row")).toHaveCount(0);
    await expect(page.getByTestId("native-sessions-no-match")).toBeVisible();
    await page.getByTestId("native-sessions-search").fill(older);
    await expect(row).toBeVisible();
    await row.getByTestId("native-session-manage").click();
    await row.getByRole("button", { name: "Open conversation" }).click();
    await expect(threadRow(page, older)).toHaveAttribute("data-creator", "unknown");
    await launched.app.close();
    launched = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
    await expect(threadRow(launched.page, older)).toBeVisible();
    const prefs = await launched.page.evaluate(() => window.omo.getPreferences());
    expect(prefs.managedThreadIds).toEqual([older]);
    expect(prefs.threadCreators?.[older]).toBeUndefined();
    const count = await launched.page.evaluate(async () => (await window.omo.request("thread/list", { limit: 100 })).data.length);
    expect(count).toBe(52);
  } finally { await launched.app.close(); }
});

test("verified native agents open on the right, retain the main selection and return on narrow screens", async () => {
  const home = tempDir("right-agent-home"), workspace = tempDir("right-agent-workspace"), userData = tempDir("right-agent-user");
  const { app, page } = await launchApp({ omo: "fake", fakeHome: home, userData, pickDir: workspace });
  try {
    const main = await newSession(page);
    await send(page, "main agent work");
    await expect(page.getByTestId("assistant-message").last()).toContainText("main agent work");
    const child = await page.evaluate(async cwd => (await window.omo.request("thread/start", { cwd })).thread, workspace);
    const parentPath = await page.evaluate(async id => (await window.omo.request("thread/list", { limit: 100 })).data.find(thread => thread.id === id)?.path, main);
    expect(parentPath).toBeTruthy();
    const lines = readFileSync(child.path!, "utf8").trimEnd().split("\n");
    lines[0] = JSON.stringify({ ...JSON.parse(lines[0]!), parentSession: parentPath });
    writeFileSync(child.path!, lines.join("\n") + "\n");
    const childFile = readFileSync(child.path!, "utf8");
    await page.evaluate(async id => window.omo.request("thread/name/set", { threadId: id, name: "Native inspection agent" }), child.id);
    await page.reload();
    await threadRow(page, main).getByRole("button").first().click();
    await expect(page.getByTestId("agent-workspace")).toHaveAttribute("data-placement", "docked");
    await expect(threadRow(page, child.id)).toHaveCount(0);
    const agent = page.getByTestId("agent-row").filter({ hasText: "Native inspection agent" });
    await expect(agent).toBeVisible();
    for (const theme of ["light", "dark"] as const) {
      await setTheme(page, theme);
      await shot(page, `right-agent-${theme}-desktop`);
    }
    await agent.click();
    await expect(page.getByTestId("composer-input")).toHaveAttribute("data-thread-id", child.id);
    await expect(threadRow(page, main)).toHaveAttribute("aria-current", "page");
    await expect(page.getByTestId("agent-header-return-main")).toBeVisible();
    await page.getByTestId("agent-header-return-main").click();
    await expect(page.getByTestId("composer-input")).toHaveAttribute("data-thread-id", main);
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(640, 850));
    await expect(page.getByTestId("agent-workspace")).toHaveCount(0);
    await page.getByTestId("agent-panel-toggle").click();
    await expect(page.getByTestId("agent-workspace")).toHaveAttribute("data-placement", "overlay");
    await shot(page, "right-agent-dark-narrow");
    await agent.click();
    await expect(page.getByTestId("agent-workspace")).toHaveCount(0);
    await expect(page.getByTestId("composer-input")).toBeVisible();
    await page.getByTestId("agent-header-return-main").click();
    await expect(page.getByTestId("composer-input")).toHaveAttribute("data-thread-id", main);
    await page.getByTestId("header-sidebar-toggle").click();
    await page.getByTestId("open-settings").click();
    await page.getByTestId("settings-nav-toggle").click();
    await page.locator('[data-section="appearance"]').click();
    await page.getByTestId("settings-theme-light").click();
    await page.keyboard.press("Escape");
    await page.getByTestId("agent-panel-toggle").click();
    await shot(page, "right-agent-light-narrow");
    await page.getByTestId("right-dock-close").click();
    await expect(page.getByTestId("composer-input")).toBeVisible();
    const listed = await page.evaluate(async () => (await window.omo.request("thread/list", { limit: 100 })).data.map(t => t.id).sort());
    expect(listed).toEqual([main, child.id].sort());
    expect(readFileSync(child.path!, "utf8")).toContain(childFile.trimEnd());
  } finally { await app.close(); }
});
